# Generated by Django 4.2.6 on 2023-10-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('TEACHER', 'Teacher')], default='USER', max_length=7, null=True),
        ),
    ]
