# Generated by Django 4.2.6 on 2023-10-19 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_customuser_temp_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('experience', models.IntegerField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='faculty_images/')),
                ('certificate', models.FileField(upload_to='faculty_certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('faculty', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentification.faculty')),
            ],
        ),
    ]
