# Generated by Django 4.2.6 on 2023-10-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_delete_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('BAN', 'ban')], default='USER', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='temp_role',
            field=models.CharField(blank=True, choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('BAN', 'ban')], default='USER', max_length=7, null=True),
        ),
    ]
