# Generated by Django 4.2.6 on 2023-11-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0008_alter_customuser_role_alter_customuser_temp_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='quiz_points',
            field=models.IntegerField(default=0),
        ),
    ]
