# Generated by Django 4.2.6 on 2023-11-21 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Family', '0001_initial'),
        ('authentification', '0009_customuser_quiz_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Family.families'),
        ),
    ]
