# Generated by Django 4.2.6 on 2023-11-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='families',
            name='family_image',
            field=models.ImageField(null=True, upload_to='family/images'),
        ),
    ]
