# Generated by Django 4.2.6 on 2023-11-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Family', '0002_families_family_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='families',
            name='instruction',
            field=models.TextField(null=True),
        ),
    ]
