# Generated by Django 4.2.6 on 2023-12-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Family', '0004_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender_username',
            new_name='sender',
        ),
    ]
