# Generated by Django 4.2.6 on 2023-12-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Family', '0005_rename_sender_username_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='families',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
