# Generated by Django 4.2.6 on 2023-11-06 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0005_discussion_discussion_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion_comment',
            old_name='reply_text',
            new_name='text',
        ),
    ]
