# Generated by Django 4.2.6 on 2023-10-22 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Courses', '0004_course_advertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name=models.Model)),
                ('document', models.ImageField(blank=True, null=True, upload_to='courses/images/')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.course_advertise')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
