# Generated by Django 4.2.6 on 2023-10-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='description',
            field=models.TextField(),
        ),
    ]
