# Generated by Django 4.2.6 on 2023-10-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_alter_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_advertise',
            name='is_vacant',
            field=models.BooleanField(default=True),
        ),
    ]
