# Generated by Django 4.2.6 on 2023-10-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0010_applications_addi_document_applications_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
