# Generated by Django 4.2.6 on 2023-10-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0014_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
