# Generated by Django 4.2.6 on 2023-11-03 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0015_alter_applications_phonenumber_and_more'),
        ('Courses', '0015_chapter_is_free'),
    ]

    operations = [
    ]
