# Generated by Django 4.2.6 on 2023-11-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testseries', '0002_testattempt_quizresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresponse',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
